name: Deploy Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: AWS
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Removing unwanted folders
        run: |
          rm -rf .git
          rm -rf .github

      - name: Sincronizar arquivos com o S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --exclude ".git/*" --exclude ".github/*"
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "s3-ingestion/website/"
